title: "CS 212 Software Development"
name: "Sophie Engle"
repository: "usf-cs212-spring2019/usf-cs212-spring2019.github.io"
timezone: "America/Los_Angeles"
permalink: /guides/:title:output_ext

collections:
  general:
    title: General Guides
    order: 1
    output: true
    permalink: /guides/:collection/:name:output_ext

  homework:
    title: Homework Guides
    order: 2
    output: true
    permalink: /guides/:collection/:name:output_ext

  projects:
    title: Project Guides
    order: 3
    output: true
    permalink: /guides/:collection/:name:output_ext

  writeups:
    title: Project Writeups
    order: 4
    output: true
    permalink: /guides/:collection/:name:output_ext
